// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetScreenObjects():Promise<main.AppResponse___github_com_wailsapp_wails_v2_internal_frontend_Screen_>;

export function StartRecording():Promise<main.AppResponse_interface____>;

export function StopRecording():Promise<main.AppResponse_interface____>;
